### PR TITLE
fix: cutoff text

### LINKED ISSUE #10: Hide cut off texts
Screen Shot 2021-09-02 at 10 55 53

Screen Shot 2021-09-17 at 17 24 50

When you currently visit rugpullindex.com (screenshot above), you can see that the x-label text showing the months, for "September", we can only see a half-cut off "S". Similarly, the same can happen on the y-axis with the prices.

Deliverables:

- For any text that can't make it into the full view; make sure to hide it: Specifically, this means that the half-cut of "S" shouldn't show up anymore.
- Write tests that reproduces and confirms this issue

### PR DESCRIPTION
**Pull request by il3ven**
Resolves #10 

### Previous
Screenshot 2021-09-20 152112

### Fixed
fixed

### Summary
Instead of hiding the text that isn't able to make it into the viewport I have added a kind of padding to the top and right side of the graph. This was achieved by modifying the following functions.

```diff
- const { x, labels } = scaleDates(offsetX, options.width, data.x);
+ const { x, labels } = scaleDates(offsetX, options.width-PADDING.RIGHT, data.x);
```

```diff
- const yScaledLabels = scalePoints(offsetY, options.height, min, max, yPoints);
+ const yScaledLabels = scalePoints(PADDING.TOP, options.height-offsetY, min, max, yPoints);
```

I have also modified the *scalePoints* function. The previous scalePoints function didn't behave the way I expected. 

For example, 
```js
scalePoints(5, 30, 6, 48, [6, 10, 22, 40]) = [ 25, 22.6190, 15.4762, 4.7619]
```

In the above example, the input range should be scaled from [5, 30] but there are output points such as 4.7619. The point 6 is the min and should be scaled to 30.

The modified scalePoints function,
```js
scalePoints(5, 30, 6, 48, [6, 10, 22, 40]) = [ 30, 27.6190, 20.4762, 9.7619 ]
```

#### Writing Tests
The test for the functions `scaleDates` and `scalePoints` should be applicable here too.

### CODE REVIEW

File: src/index.mjs [hunk 1]
```diff
@@ -243,16 +248,29 @@ export function getMinMax(range, margin = 0) {
...
+ * @param min {number} Minimum value of the input range
+ * @param max {Number} Maximum value of the input range
+ * @param range {Number[]} Points within the range [min, max] to be scaled
+ * @returns {Number[]} Array of scaled points
+ */
 export function scalePoints(from, to, min, max, range) {
-  const minAllowed = from;
-  const maxAllowed = to;
-
   // NOTE: For explaination see: https://stackoverflow.com/a/31687097/1263876
```
Comment (TimDaub) [inline src/index.mjs:271]: This comment specifically references a Stackoverflow comment about the now-removed scaling function. If we want to go along with the newly proposed function, we should also remove the comment.

File: src/index.mjs [hunk 2]
```diff
@@ -243,16 +248,29 @@ export function getMinMax(range, margin = 0) {
...
+/**
+ * Scale the given points into the range [from, to].
+ * 
+ * Points closer to min will be scaled closer to 'to'.
+ * Points closer to max will be scaled closer to 'from'.
+ * 
+ * Example - scalePoints(5, 30, 8, 20, [8, 9, 10, 11, 15, 16, 20])
+ * = [30, 27.916666666666668, 25.833333333333332, 23.75, 15.416666666666666, 13.333333333333332, 5]
+ * 
+ * Note: It is not necesarry for input range to include
```
Comment (TimDaub) [inline src/index.mjs:260]: Would you mind elaborating more on this note? I don't understand what it means.

File: src/index.mjs (hunk 1 above)
Comment (il3ven) [reply src/index.mjs:271]: We can keep [this](https://stackoverflow.com/a/5295202/11370119) answer in the comments. The current function is based on that answer but instead of scaling the min to `a` we scale it to `b` and the max to `a`. Essentially reversing the output of the function in that answer.

Comment (TimDaub) [reply src/index.mjs:271]: ok 👍🏼

**Comment by TimDaub** [comment]
I've found one bug that happens when deploying the chart in this branch to rugpullindex.com:

Screen Shot 2021-09-20 at 18 11 05

You can see that above "350", we'd expect another one of those grey horizontal lines - but there's none.
For you to test, I've now updated master (fa740d3) with the latest test data. I went into your branch and applied master. Here's the result I get:

Screen Shot 2021-09-20 at 18 10 10

So it's reproducible. Here's what I suggest:

- We render the top grey horizontal line too, independently of the margin. We do the same thing for any vertical grey lines. Or what do you think?

File: src/index.mjs (hunk 2 above)
Comment (il3ven) [reply src/index.mjs:260]: I meant that the range can be anything between `[min, max]`.

Suppose the `min = 0` and `max = 10`, both the following are valid range
- `range = [5, 6, 7]`
- `range = [1, 5, 6, 7, 10]`

The min doesn't have to be the minimum element present in the range. Same goes for max. While reading the code at first I thought that was the case.

**Comment by il3ven** [comment]
> We render the top grey horizontal line too, independently of the margin. We do the same thing for any vertical grey lines. Or what do you think?

Idea sounds great.

This (ab6f724d647903eca3dbdbaed463a3df773b696b) is how I am generating the position for the grid lines. 

image
> Output using latest commit (ab6f724d647903eca3dbdbaed463a3df773b696b)

If I generated the grid lines using the code below then the lines were not aligned with the labels. (See photo)

```js
const yGridLines = scalePoints(0, options.height-offsetY, min, max, yPoints);
```

image

**Comment by il3ven** [comment]
I have also added a commit changing a variable name (af2b33c40aab9bd66371ea785786478e397ab79a). This is a subjective opinion. You can also revert or change it.
